[2023-05-15 13:29:45,997] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-05-15 13:29:46,002] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [queued]>
[2023-05-15 13:29:46,002] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-15 13:29:46,002] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-05-15 13:29:46,003] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-15 13:29:46,015] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-12-26 00:00:00+00:00
[2023-05-15 13:29:46,019] {standard_task_runner.py:52} INFO - Started process 68219 to run task
[2023-05-15 13:29:46,023] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-12-26T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpl8g5g8ky', '--error-file', '/tmp/tmp7efly1_d']
[2023-05-15 13:29:46,023] {standard_task_runner.py:80} INFO - Job 87: Subtask cria_pasta
[2023-05-15 13:29:46,062] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-26T00:00:00+00:00 [running]> on host v-Default-string
[2023-05-15 13:29:46,106] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-12-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-26T00:00:00+00:00
[2023-05-15 13:29:46,106] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-05-15 13:29:46,107] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2023-01-02"']
[2023-05-15 13:29:46,115] {subprocess.py:85} INFO - Output:
[2023-05-15 13:29:46,118] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/home/millenagena’: Permission denied
[2023-05-15 13:29:46,118] {subprocess.py:96} INFO - Command exited with return code 1
[2023-05-15 13:29:46,126] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/v/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-15 13:29:46,128] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221226T000000, start_date=20230515T162945, end_date=20230515T162946
[2023-05-15 13:29:46,141] {standard_task_runner.py:92} ERROR - Failed to execute job 87 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 68219)
[2023-05-15 13:29:46,154] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-15 13:29:46,186] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
