[2023-05-15 14:05:32,481] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta manual__2023-05-15T17:05:29.365467+00:00 [queued]>
[2023-05-15 14:05:32,485] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta manual__2023-05-15T17:05:29.365467+00:00 [queued]>
[2023-05-15 14:05:32,485] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-15 14:05:32,486] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-05-15 14:05:32,486] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-15 14:05:32,499] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-05-15 17:05:29.365467+00:00
[2023-05-15 14:05:32,503] {standard_task_runner.py:52} INFO - Started process 79883 to run task
[2023-05-15 14:05:32,507] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'manual__2023-05-15T17:05:29.365467+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmptp4rqpu3', '--error-file', '/tmp/tmpp2r29g9h']
[2023-05-15 14:05:32,508] {standard_task_runner.py:80} INFO - Job 107: Subtask cria_pasta
[2023-05-15 14:05:32,540] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta manual__2023-05-15T17:05:29.365467+00:00 [running]> on host v-Default-string
[2023-05-15 14:05:32,592] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-05-15T17:05:29.365467+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-15T17:05:29.365467+00:00
[2023-05-15 14:05:32,593] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-05-15 14:05:32,593] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2023-05-15"']
[2023-05-15 14:05:32,600] {subprocess.py:85} INFO - Output:
[2023-05-15 14:05:32,602] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/home/millenagena’: Permission denied
[2023-05-15 14:05:32,603] {subprocess.py:96} INFO - Command exited with return code 1
[2023-05-15 14:05:32,611] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/v/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-15 14:05:32,613] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230515T170529, start_date=20230515T170532, end_date=20230515T170532
[2023-05-15 14:05:32,624] {standard_task_runner.py:92} ERROR - Failed to execute job 107 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 79883)
[2023-05-15 14:05:32,638] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-15 14:05:32,670] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
