[2023-05-15 13:29:40,722] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-12T00:00:00+00:00 [queued]>
[2023-05-15 13:29:40,727] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-12T00:00:00+00:00 [queued]>
[2023-05-15 13:29:40,727] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-15 13:29:40,727] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-05-15 13:29:40,727] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-15 13:29:40,740] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-12-12 00:00:00+00:00
[2023-05-15 13:29:40,743] {standard_task_runner.py:52} INFO - Started process 68121 to run task
[2023-05-15 13:29:40,747] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-12-12T00:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp3u14316d', '--error-file', '/tmp/tmpk4j_grdm']
[2023-05-15 13:29:40,748] {standard_task_runner.py:80} INFO - Job 85: Subtask cria_pasta
[2023-05-15 13:29:40,785] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-12-12T00:00:00+00:00 [running]> on host v-Default-string
[2023-05-15 13:29:40,831] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-12-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-12T00:00:00+00:00
[2023-05-15 13:29:40,832] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-05-15 13:29:40,833] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2022-12-19"']
[2023-05-15 13:29:40,841] {subprocess.py:85} INFO - Output:
[2023-05-15 13:29:40,843] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/home/millenagena’: Permission denied
[2023-05-15 13:29:40,843] {subprocess.py:96} INFO - Command exited with return code 1
[2023-05-15 13:29:40,852] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/v/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-15 13:29:40,854] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221212T000000, start_date=20230515T162940, end_date=20230515T162940
[2023-05-15 13:29:40,866] {standard_task_runner.py:92} ERROR - Failed to execute job 85 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 68121)
[2023-05-15 13:29:40,878] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-15 13:29:40,911] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
