[2023-05-15 13:30:23,693] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-05-15 13:30:23,699] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-04-10T00:00:00+00:00 [queued]>
[2023-05-15 13:30:23,699] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-15 13:30:23,699] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-05-15 13:30:23,699] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-15 13:30:23,711] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-04-10 00:00:00+00:00
[2023-05-15 13:30:23,715] {standard_task_runner.py:52} INFO - Started process 69090 to run task
[2023-05-15 13:30:23,718] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-04-10T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmplz1g3xbr', '--error-file', '/tmp/tmpojfz1g58']
[2023-05-15 13:30:23,718] {standard_task_runner.py:80} INFO - Job 102: Subtask cria_pasta
[2023-05-15 13:30:23,751] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-04-10T00:00:00+00:00 [running]> on host v-Default-string
[2023-05-15 13:30:23,801] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2023-04-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-10T00:00:00+00:00
[2023-05-15 13:30:23,802] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-05-15 13:30:23,802] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/millenagena/Documents/airflowalura/semana=2023-04-17"']
[2023-05-15 13:30:23,811] {subprocess.py:85} INFO - Output:
[2023-05-15 13:30:23,813] {subprocess.py:92} INFO - mkdir: cannot create directory ‘/home/millenagena’: Permission denied
[2023-05-15 13:30:23,813] {subprocess.py:96} INFO - Command exited with return code 1
[2023-05-15 13:30:23,820] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/v/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-15 13:30:23,822] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230410T000000, start_date=20230515T163023, end_date=20230515T163023
[2023-05-15 13:30:23,831] {standard_task_runner.py:92} ERROR - Failed to execute job 102 for task cria_pasta (Bash command failed. The command returned a non-zero exit code 1.; 69090)
[2023-05-15 13:30:23,849] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-05-15 13:30:23,880] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
